export const ADD_TODO = "ADD_TODO";
export const RETRIEVE_DATA = "RETRIEVE_DATA";
export const RETRIEVE_DATA_FAILURE = "RETRIEVE_DATA_FAILURE";
export const SET_VISIBILITY_FILER = "SET_VISIBILITY_FILER";
export const TOGGLE_TODO = "TOGGLE_TODO";
