export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
export const RETRIEVE_DATA = "RETRIEVE_DATA";
export const RETRIEVE_DATA_FAILURE = "RETRIEVE_DATA_FAILURE";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const SET_VISIBILITY_FILTER_FAILURE = "SET_VISIBILITY_FILTER_FAILURE";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE";
